title = "Vo Vinh"
languageCode = "en-us"
baseUrl = "https://gswcapital.github.io/"
theme = "casper"


# Define how many pages appear per site
paginate = 5
paginatePath = "page"

[params]
    site_author = "VÃµ Vinh"
    site_description = "Enthusiastic & Ambitious"
    location = "Ho Chi Minh City"

    author = "vovinh"

    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "images/glorevenhite-thumb.jpeg"
    header_background = "images/desk.jpg"
    header_title = "Customizable header title"
    copyright = "Powered by [Hugo](http://gohugo.io)."


    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "glorevenhite"
    facebook  = "truongvinh.vo"
    linkedin  = "votruongvinh"
    github    = "glorevenhite"
    gplus     = "vinh.votruong"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Home"
  weight = -130
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Investment"
  weight = -110
  identifier = "investment"
  url = "/categories/investment"

[[menu.main]]
  name = "Commentary"
  weight = -100
  identifier = "commentary"
  url = "/categories/commentary"

[[menu.main]]
  name = "Invest in Vietnam"
  weight = -90
  identifier = "guidance"
  url = "/categories/guidance"

[[menu.main]]
  name = "Blogs"
  weight = -10
  identifier = "blog"
  url = "/categories/blog"

[[menu.main]]
  name = "About me"
  weight = 0
  identifier = "about"
  url = "/about"
